### ISSUE TITLE
LaTeX Error: Command \BibTeX already defined.

### ISSUE THREAD

**Issue by bradfordboyle** [DrexelPhysics/drexel-thesis#4]
Running `make` on a fresh clone gives the following error message:
    ! LaTeX Error: Command \BibTeX already defined.
                   Or name \end... illegal, see p.192 of the manual.

```
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.174 % \newcommand{\BibTeX}{{\scshape Bib}\TeX}
```

Rolling back to a976bae builds successfully.

**Comment by rcanzanese** [comment]
I confirmed this bug in my LaTeX distribution (pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014))

`\BibTeX` is defined in doc.sty, which is included by ltxdoc.cls.

If the concern is that there are others using LaTeX distributions that don't provide a `\BibTeX` command, then this bug can be addressed using

```
\providecommand{\BibTeX}{{\scshape Bib}\TeX}
```

Otherwise, this line can be removed.

**Comment by wking** [comment]
On Tue, May 19, 2015 at 12:53:37PM -0700, Ray Canzanese wrote:

> If the concern is that there are others using LaTeX distributions
> that don't provide a `\BibTeX` command, then ….  Otherwise, this
> line can be removed.

I'm fine removing the line.
